In [36]:
# python notebook for Make Your Own Neural Network
# code for a 3-layer neural network, and code for learning the MNIST dataset
# (c) Tariq Rashid, 2016
# license is GPLv2

In [2]:
import numpy
# scipy.special for the sigmoid function expit()
import scipy.special
# library for plotting arrays
import matplotlib.pyplot
# ensure the plots are inside this notebook, not an external window
%matplotlib inline

In [3]:
# neural network class definition
class neuralNetwork:

    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc 
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))

        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        print("end init.")
        pass

    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        print("inputs")
        print(inputs)
        print("targets")
        print(targets)
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        print("Se realizó multiplicación de matrices y función de activación de hidden")
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("Se realizó multiplicación de matrices y función de activación de final")
        print(final_outputs)
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        print("El error es: "+str(output_errors))
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        print("end train.")
        pass

    
    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("end query.")
        return final_outputs

In [37]:
# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# learning rate
learning_rate = 0.1

print("# of input nodes: "+str(input_nodes)+"\n# of hidden nodes: "+str(hidden_nodes)+"\n# of output nodes: "+str(output_nodes))
# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)
print("The neural network was created")

# of input nodes: 3
# of hidden nodes: 3
# of output nodes: 3
end init.
The neural network was created


In [38]:
# load the mnist training data CSV file into a list
training_data_file = open("mnist_dataset/contador.csv", 'r')
training_data_list = training_data_file.readlines()
training_data_file.close()

In [39]:
# train the neural network

# epochs is the number of times the training data set is used for training
epochs = 150

for e in range(epochs):
    # go through all records in the training data set
    contador = 1
    for record in training_data_list:
        # split the record by the ',' commas
        all_values = record.split(',')
        # scale and shift the inputs
        inputs = (numpy.asfarray(all_values[0:3]) / 1.0) + 0.00
        # inputs = (numpy.asfarray(all_values[0:3]) / 255.0 * 0.99) + 0.01
        # create the target output values (all 0.01, except the desired label which is 0.99)
        # targets = numpy.zeros(output_nodes) + 0.01
        target_values = training_data_list[contador].split(',')
        targets = (numpy.asfarray(target_values[0:3]) / 1.0) + 0.00
        print("inputs ", inputs)
        print("targets ", targets)
        # all_values[0] is the target label for this record
        # targets[int(all_values[0])] = 0.99
        n.train(inputs, targets)
        contador += 1
        if(contador == 8):
            contador = 0
    pass

inputs  [ 0.  0.  0.]
targets  [ 0.  0.  1.]
inputs
[[ 0.]
 [ 0.]
 [ 0.]]
targets
[[ 0.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.4735653 ]
 [ 0.43304912]
 [ 0.50036858]]
El error es: [[-0.4735653 ]
 [-0.43304912]
 [ 0.49963142]]
end train.
inputs  [ 0.  0.  1.]
targets  [ 0.  1.  0.]
inputs
[[ 0.]
 [ 0.]
 [ 1.]]
targets
[[ 0.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.47198619]
 [ 0.50019427]
 [ 0.51229752]]
El error es: [[-0.47198619]
 [ 0.49980573]
 [-0.51229752]]
end train.
inputs  [ 0.  1.  0.]
targets  [ 0.  1.  1.]
inputs
[[ 0.]
 [ 1.]
 [ 0.]]
targets
[[ 0.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.45633194]
 [ 0.4335374

Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.45761195]
 [ 0.49857336]
 [ 0.50091187]]
El error es: [[ 0.54238805]
 [-0.49857336]
 [-0.50091187]]
end train.
inputs  [ 1.  0.  0.]
targets  [ 1.  0.  1.]
inputs
[[ 1.]
 [ 0.]
 [ 0.]]
targets
[[ 1.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48646373]
 [ 0.45243435]
 [ 0.52896585]]
El error es: [[ 0.51353627]
 [-0.45243435]
 [ 0.47103415]]
end train.
inputs  [ 1.  0.  1.]
targets  [ 1.  1.  0.]
inputs
[[ 1.]
 [ 0.]
 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48482134]
 [ 0.51259592]
 [ 0.52553608]]
El error es: [[ 0.51517866]
 [ 0.48740408]
 [-0.52553608]]
end train.
inputs  [ 1.  1

targets
[[ 0.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.46054968]
 [ 0.45109008]
 [ 0.5154067 ]]
El error es: [[-0.46054968]
 [ 0.54890992]
 [ 0.4845933 ]]
end train.
inputs  [ 0.  1.  1.]
targets  [ 1.  0.  0.]
inputs
[[ 0.]
 [ 1.]
 [ 1.]]
targets
[[ 1.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.45625687]
 [ 0.50036022]
 [ 0.50280831]]
El error es: [[ 0.54374313]
 [-0.50036022]
 [-0.50280831]]
end train.
inputs  [ 1.  0.  0.]
targets  [ 1.  0.  1.]
inputs
[[ 1.]
 [ 0.]
 [ 0.]]
targets
[[ 1.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.49250837]
 [ 0.45682652]
 [ 0.54751487]]
El error es: [[ 0.50749163]
 [-0.45682652]
 [ 0.4524851

inputs  [ 1.  0.  1.]
targets  [ 1.  1.  0.]
inputs
[[ 1.]
 [ 0.]
 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48814906]
 [ 0.51315314]
 [ 0.53159554]]
El error es: [[ 0.51185094]
 [ 0.48684686]
 [-0.53159554]]
end train.
inputs  [ 1.  1.  0.]
targets  [ 1.  1.  1.]
inputs
[[ 1.]
 [ 1.]
 [ 0.]]
targets
[[ 1.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48572521]
 [ 0.47040329]
 [ 0.5436887 ]]
El error es: [[ 0.51427479]
 [ 0.52959671]
 [ 0.4563113 ]]
end train.
inputs  [ 1.  1.  1.]
targets  [ 0.  0.  0.]
inputs
[[ 1.]
 [ 1.]
 [ 1.]]
targets
[[ 0.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.47889411]
 [ 0.5145868

targets
[[ 1.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.49135446]
 [ 0.47454715]
 [ 0.55977407]]
El error es: [[ 0.50864554]
 [ 0.52545285]
 [ 0.44022593]]
end train.
inputs  [ 1.  1.  1.]
targets  [ 0.  0.  0.]
inputs
[[ 1.]
 [ 1.]
 [ 1.]]
targets
[[ 0.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.4784552 ]
 [ 0.5153581 ]
 [ 0.51644641]]
El error es: [[-0.4784552 ]
 [-0.5153581 ]
 [-0.51644641]]
end train.
inputs  [ 0.  0.  0.]
targets  [ 0.  0.  1.]
inputs
[[ 0.]
 [ 0.]
 [ 0.]]
targets
[[ 0.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48444759]
 [ 0.45192296]
 [ 0.57129473]]
El error es: [[-0.48444759]
 [-0.45192296]
 [ 0.4287052

targets
[[ 1.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.43932394]
 [ 0.50268613]
 [ 0.49081689]]
El error es: [[ 0.56067606]
 [-0.50268613]
 [-0.49081689]]
end train.
inputs  [ 1.  0.  0.]
targets  [ 1.  0.  1.]
inputs
[[ 1.]
 [ 0.]
 [ 0.]]
targets
[[ 1.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.5165221 ]
 [ 0.45854201]
 [ 0.62075578]]
El error es: [[ 0.4834779 ]
 [-0.45854201]
 [ 0.37924422]]
end train.
inputs  [ 1.  0.  1.]
targets  [ 1.  1.  0.]
inputs
[[ 1.]
 [ 0.]
 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.4876936 ]
 [ 0.51190986]
 [ 0.53498744]]
El error es: [[ 0.5123064 ]
 [ 0.48809014]
 [-0.5349874

 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48540476]
 [ 0.51059512]
 [ 0.53369568]]
El error es: [[ 0.51459524]
 [ 0.48940488]
 [-0.53369568]]
end train.
inputs  [ 1.  1.  0.]
targets  [ 1.  1.  1.]
inputs
[[ 1.]
 [ 1.]
 [ 0.]]
targets
[[ 1.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.50834644]
 [ 0.47664343]
 [ 0.6037973 ]]
El error es: [[ 0.49165356]
 [ 0.52335657]
 [ 0.3962027 ]]
end train.
inputs  [ 1.  1.  1.]
targets  [ 0.  0.  0.]
inputs
[[ 1.]
 [ 1.]
 [ 1.]]
targets
[[ 0.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.47315016]
 [ 0.51545873]
 [ 0.51052496]]
El error es: [[-0.47315016]
 [-0.51545873]
 [-0

targets
[[ 0.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.46698851]
 [ 0.51479807]
 [ 0.50239644]]
El error es: [[-0.46698851]
 [-0.51479807]
 [-0.50239644]]
end train.
inputs  [ 0.  0.  0.]
targets  [ 0.  0.  1.]
inputs
[[ 0.]
 [ 0.]
 [ 0.]]
targets
[[ 0.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.49222106]
 [ 0.4578052 ]
 [ 0.6178411 ]]
El error es: [[-0.49222106]
 [-0.4578052 ]
 [ 0.3821589 ]]
end train.
inputs  [ 0.  0.  1.]
targets  [ 0.  1.  0.]
inputs
[[ 0.]
 [ 0.]
 [ 1.]]
targets
[[ 0.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.43134685]
 [ 0.49912718]
 [ 0.47703478]]
El error es: [[-0.43134685]
 [ 0.50087282]
 [-0.4770347

targets  [ 1.  0.  1.]
inputs
[[ 1.]
 [ 0.]
 [ 0.]]
targets
[[ 1.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.55565181]
 [ 0.44789212]
 [ 0.7160709 ]]
El error es: [[ 0.44434819]
 [-0.44789212]
 [ 0.2839291 ]]
end train.
inputs  [ 1.  0.  1.]
targets  [ 1.  1.  0.]
inputs
[[ 1.]
 [ 0.]
 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.47244527]
 [ 0.50633   ]
 [ 0.51756032]]
El error es: [[ 0.52755473]
 [ 0.49367   ]
 [-0.51756032]]
end train.
inputs  [ 1.  1.  0.]
targets  [ 1.  1.  1.]
inputs
[[ 1.]
 [ 1.]
 [ 0.]]
targets
[[ 1.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.53308662]
 [ 0.47246409]
 [ 0.6622617 ]]
El 

Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.57186469]
 [ 0.44487262]
 [ 0.74906452]]
El error es: [[ 0.42813531]
 [-0.44487262]
 [ 0.25093548]]
end train.
inputs  [ 1.  0.  1.]
targets  [ 1.  1.  0.]
inputs
[[ 1.]
 [ 0.]
 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.4602586 ]
 [ 0.50375404]
 [ 0.49806424]]
El error es: [[ 0.5397414 ]
 [ 0.49624596]
 [-0.49806424]]
end train.
inputs  [ 1.  1.  0.]
targets  [ 1.  1.  1.]
inputs
[[ 1.]
 [ 1.]
 [ 0.]]
targets
[[ 1.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.54808402]
 [ 0.47017338]
 [ 0.69558639]]
El error es: [[ 0.45191598]
 [ 0.52982662]
 [ 0.30441361]]
end train.
inputs  [ 1.  1

inputs
[[ 0.]
 [ 0.]
 [ 1.]]
targets
[[ 0.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.3821061]
 [ 0.4948616]
 [ 0.3750618]]
El error es: [[-0.3821061]
 [ 0.5051384]
 [-0.3750618]]
end train.
inputs  [ 0.  1.  0.]
targets  [ 0.  1.  1.]
inputs
[[ 0.]
 [ 1.]
 [ 0.]]
targets
[[ 0.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.46810833]
 [ 0.49313523]
 [ 0.56774846]]
El error es: [[-0.46810833]
 [ 0.50686477]
 [ 0.43225154]]
end train.
inputs  [ 0.  1.  1.]
targets  [ 1.  0.  0.]
inputs
[[ 0.]
 [ 1.]
 [ 1.]]
targets
[[ 1.]
 [ 0.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.36714787]
 [ 0.50155907]
 [ 0.35655295]]
El error es: [[ 0.63285213]
 [-0

inputs
[[ 1.]
 [ 0.]
 [ 0.]]
targets
[[ 1.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.60199511]
 [ 0.44276894]
 [ 0.80510342]]
El error es: [[ 0.39800489]
 [-0.44276894]
 [ 0.19489658]]
end train.
inputs  [ 1.  0.  1.]
targets  [ 1.  1.  0.]
inputs
[[ 1.]
 [ 0.]
 [ 1.]]
targets
[[ 1.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.43122037]
 [ 0.49968703]
 [ 0.43974511]]
El error es: [[ 0.56877963]
 [ 0.50031297]
 [-0.43974511]]
end train.
inputs  [ 1.  1.  0.]
targets  [ 1.  1.  1.]
inputs
[[ 1.]
 [ 1.]
 [ 0.]]
targets
[[ 1.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.57898321]
 [ 0.4690828 ]
 [ 0.75984094]]
El error es: [[ 0.42101679

inputs  [ 0.  0.  0.]
targets  [ 0.  0.  1.]
inputs
[[ 0.]
 [ 0.]
 [ 0.]]
targets
[[ 0.]
 [ 0.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.51848467]
 [ 0.47228963]
 [ 0.65932579]]
El error es: [[-0.51848467]
 [-0.47228963]
 [ 0.34067421]]
end train.
inputs  [ 0.  0.  1.]
targets  [ 0.  1.  0.]
inputs
[[ 0.]
 [ 0.]
 [ 1.]]
targets
[[ 0.]
 [ 1.]
 [ 0.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.3559342 ]
 [ 0.49485416]
 [ 0.29411499]]
El error es: [[-0.3559342 ]
 [ 0.50514584]
 [-0.29411499]]
end train.
inputs  [ 0.  1.  0.]
targets  [ 0.  1.  1.]
inputs
[[ 0.]
 [ 1.]
 [ 0.]]
targets
[[ 0.]
 [ 1.]
 [ 1.]]
Se realizó multiplicación de matrices y función de activación de hidden
Se realizó multiplicación de matrices y función de activación de final
[[ 0.48042577]
 [ 0.5064106

In [40]:
# load the mnist test data CSV file into a list
test_data_file = open("mnist_dataset/contador.csv", 'r')
test_data_list = test_data_file.readlines()
test_data_file.close()

In [41]:
# test the neural network

# scorecard for how well the network performs, initially empty
scorecard = []

# go through all the records in the test data set
for record in test_data_list:
    # split the record by the ',' commas
    all_values = record.split(',')
    # correct answer is first value
    correct_label = int(all_values[0])
    # scale and shift the inputs
    inputs = (numpy.asfarray(all_values[0:3]) / 1.0) + 0.00
    # query the network
    outputs = n.query(inputs)
    print ("Inputs: ", inputs)
    print("Outputs: ", outputs)
    # the index of the highest value corresponds to the label
    label = numpy.argmax(outputs)
    # append correct or incorrect to list
    if (label == correct_label):
        # network's answer matches correct answer, add 1 to scorecard
        scorecard.append(1)
    else:
        # network's answer doesn't match correct answer, add 0 to scorecard
        scorecard.append(0)
        pass
    
    pass

end query.
Inputs:  [ 0.  0.  0.]
Outputs:  [[ 0.52233906]
 [ 0.47553487]
 [ 0.66653983]]
end query.
Inputs:  [ 0.  0.  1.]
Outputs:  [[ 0.35082083]
 [ 0.49679711]
 [ 0.26769333]]
end query.
Inputs:  [ 0.  1.  0.]
Outputs:  [[ 0.4896211 ]
 [ 0.51275313]
 [ 0.59267342]]
end query.
Inputs:  [ 0.  1.  1.]
Outputs:  [[ 0.34591703]
 [ 0.50388539]
 [ 0.26027205]]
end query.
Inputs:  [ 1.  0.  0.]
Outputs:  [[ 0.63142224]
 [ 0.44439849]
 [ 0.85036299]]
end query.
Inputs:  [ 1.  0.  1.]
Outputs:  [[ 0.40666208]
 [ 0.49831752]
 [ 0.37146092]]
end query.
Inputs:  [ 1.  1.  0.]
Outputs:  [[ 0.60935382]
 [ 0.47485146]
 [ 0.81855207]]
end query.
Inputs:  [ 1.  1.  1.]
Outputs:  [[ 0.38962677]
 [ 0.51211551]
 [ 0.33896699]]


In [21]:
# calculate the performance score, the fraction of correct answers
scorecard_array = numpy.asarray(scorecard)
print ("performance = ", scorecard_array.sum() / scorecard_array.size)

performance =  0.25
